apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
  namespace: hello-go-pre
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
      - name: hello-go
        image: grvsoni/hello-go:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6001
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 6001
          initialDelaySeconds: 5
          periodSeconds: 5
