apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
  namespace: hello-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
      - name: hello-go
        image: hello-go:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6001
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-go
  namespace: hello-go
spec:
  selector:
    app: hello-go
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6001
  type: ClusterIP 