apiVersion: v1
kind: Service
metadata:
  name: hello-go
  namespace: hello-go-pre
spec:
  selector:
    app: hello-go
  ports:
  - port: 6001
    targetPort: 6001
  type: LoadBalancer
  # Adding annotations for Rancher Desktop / k3s to help with LoadBalancer access
  externalTrafficPolicy: Cluster
